# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the test_build branch
  push:
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Add Paparazzi PPA for ivy-c-dev
      - name: Add pprz PPA
        run: sudo add-apt-repository -y ppa:paparazzi-uav/ppa

    # Install dependencies
      - name: Install dependencies
        run: sudo apt install ivy-c-dev libboost-system-dev libsqlite3-dev libzip-dev qtbase5-dev libqt5svg5-dev libproj-dev mesa-common-dev libglu1-mesa-dev patchelf
      
      - name: setup env
        run: export WD=$GITHUB_WORKSPACE
      
      - name: build libs
        run: $GITHUB_WORKSPACE/build.sh libs
      
      - name: build app
        run: BUILD_TARGET=BUILD_DEB_20_04 $GITHUB_WORKSPACE/build.sh app
      
      - name: make deb
        run: $GITHUB_WORKSPACE/make_release.sh
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ${{ github.workspace }}/misc/release_body.md
          draft: false
          prerelease: false
              
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: pprzgcs.deb
          asset_name: pprzgcs_${{ runner.os }}.deb
          asset_content_type: application/vnd.debian.binary-package
        
